### ISSUE TITLE
Add origin_eldest_sibling:0 “Eldest Sibling(s?)” for localization purpose

### ISSUE THREAD

**Issue by ildallo** [n1ghthavvk/stellaris-evorin#19]
https://github.com/n1ghthavvk/stellaris-evorin/blob/140f7504e185c9c9308dfaa1a524ce586c69f32a/mod/preview_origins/localisation/00_emo_l_english.yml#L38

**Comment by n1ghthavvk** [comment]
Ah, thanks for pointing this out. I'll fix it with the next update (probably at the end of the upcoming week).

**Comment by n1ghthavvk** [comment]
Fixed in the latest release.
